<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=windows-1252"/>
	<title></title>
	<meta name="generator" content="LibreOffice 7.1.1.2 (Windows)"/>
	<meta name="created" content="2021-04-14T17:57:41.461000000"/>
	<meta name="changed" content="2021-04-14T17:59:28.111000000"/>
	<style type="text/css">
		@page { size: 8.5in 11in; margin: 0.79in }
		p { margin-bottom: 0.1in; line-height: 115%; background: transparent }
		pre { background: transparent }
		pre.western { font-family: "Liberation Mono", monospace; font-size: 10pt }
		pre.cjk { font-family: "NSimSun", monospace; font-size: 10pt }
		pre.ctl { font-family: "Liberation Mono", monospace; font-size: 10pt }
	</style>
</head>
<body lang="en-US" link="#000080" vlink="#800000" dir="ltr"><pre class="western">[build]
publish = &quot;public&quot;
command = &quot;hugo --gc &ndash;minify&quot;

<a name="a85a"></a>[context.production.environment]
HUGO_VERSION = &quot;0.54.0&quot;
HUGO_ENV = &quot;production&quot;
HUGO_ENABLEGITINFO = &quot;true&quot;

<a name="4bd1"></a>[context.split1]
command = &quot;hugo --gc --minify &ndash;enableGitInfo&quot;

<a name="0b0b"></a>[context.split1.environment]
HUGO_VERSION = &quot;0.54.0&quot;
HUGO_ENV = &quot;production&quot;

<a name="c75b"></a>[context.deploy-preview]
command = &quot;hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL&quot;

<a name="213d"></a>[context.deploy-preview.environment]
HUGO_VERSION = &quot;0.54.0&quot;

<a name="ae37"></a>[context.branch-deploy]
command = &quot;hugo --gc --minify -b $DEPLOY_PRIME_URL&quot;

<a name="c2a3"></a>[context.branch-deploy.environment]
HUGO_VERSION = &quot;0.54.0&quot;

<a name="3c71"></a>[context.next.environment]
HUGO_ENABLEGITINFO = &quot;true&quot;</pre>
</body>
</html>